name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Node.js (GitHub NPM Registry)
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sunsreddit'
          node-version-file: 'package.json'
      - name: CI/CD
        run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm run test
